version: '2'
services:

    inbound_proxy:
        build: ./proxy
        restart: always
        container_name: inbound_proxy_prod

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        volumes:
            - ../etc/ssl:/etc/nginx/ssl

        ports:
            - "80:80"
            - "443:443"

        environment:
            - TZ=America/New_York
            - LETSENCRYPT=true
            - LE_EMAIL=george@georgekaplan.xyz
            - LE_FQDN=g-s-k.space

    client:
      build: ../client
      container_name: client_prod

    server:
      build: ../server
      container_name: server_prod
