version: '3.4'
services:

  inbound_proxy:
    image: nginx
    restart: always
    container_name: inbound_proxy_dev
    logging:
      driver: json-file
      options:
          max-size: "10m"
          max-file: "5"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  client:
    build:
      context: ../client
      target: dev
    container_name: client_dev
    volumes:
      - ../client:/usr/src/app

  server:
    build:
      context: ../server
      target: dev
    container_name: server_dev
    volumes:
      - ../server:/usr/src/app
