version: "3.4"

services:
  inbound_proxy:
    image: jerj/gsk-space-proxy
    restart: always
    container_name: gsk_proxy
    ports:
      - "80:80"
    depends_on:
      - client
      - server

  client:
    image: jerj/gsk-space-client
    container_name: gsk_client

  server:
    image: jerj/gsk-space-server
    container_name: gsk_server
