version: '2'
services:

    nginx:
        image: nginx
        hostname: nginx
        restart: always
        container_name: nginx

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        volumes:
          - ./proxy/nginx.conf:/etc/nginx/nginx.conf

        ports:
            - "80:80"

    client:
      build: 
        context: ../client
        dockerfile: Dockerfile.dev
      container_name: gsk-space

      volumes:
        - ../client:/usr/src/app

    server:
      build: 
        context: ../server
        dockerfile: Dockerfile.dev
      container_name: crud-server

      volumes:
        - ../server:/usr/src/app
